### ISSUE TITLE
Desarrollar nuevas características y arreglar bugs en un branch diferente de master

### ISSUE THREAD

**Issue by imartinezortiz** [patsancu/comienzoProyecto#18]
Es recomendable mantener la versión estable del proyecto en el branch master y desarrollar y realizar pruebas siempre en un branch aparte que también puede estar publicado en github. La idea es que cuando te descargas el proyecto siempre puedas desplegar la aplicación (en el estado en el que esté) con el contenido de master.

**Comment by patsancu** [comment]
Ok, lo tendré en cuenta.
